[package]
name = "build-app"
version = "0.1.0"
authors = ["Micah Cooper <micah+github@mrmicahcooper.com>"]
edition = "2018"

[dependencies]
handlebars = "2.0.1"
serde_json = "1.0.40"
serde = { version = "1.0.98", features = ["derive"] }
glob = "0.3.0"
regex = "1"
